name: 'Lambda Deployment'
description: 'Deploy to Lambda'
inputs:
  aws_region:
    description: 'AWS Region'  
  function_name:
    description: 'Name of the function'
  s3_bucket:
    description: 'S3 Bucket name'
  s3_key:
    description: 'S3 Key name'
  zip_file:
    description: 'AWS lambda zip file'
  create_function:
    description: 'Flag for creating a new lambda function'
    default: 'false'
  runtime:
    description: 'Lambda runtime'
  memory:
    description: 'Lambda memory'
  environment_variables:
    description: 'Environment variables'
  role_arn:
    description: 'Role ARN'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  